# Proyek Akhir Kelompok 9

### Tema : Prediksi Indeks Pencemaran Lingkungan DKI Jakarta

- I Wayan Krisna Gita Santika
- Eka Agustina
- Slamet Mahendra


### Import Library

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore') 

### Load Data

Data diambil dari https://data.jakarta.go.id/dataset/indeks-standar-pencemaran-udara-ispu-tahun-2020

In [2]:
data_train = pd.read_csv('clean_data_train.csv')
data_test = pd.read_csv('clean_data_test.csv')

In [3]:
data_train.shape

(2358, 9)

In [4]:
data_test.shape

(260, 9)

Keterangan Fitur dan Label

1. tanggal : Tanggal pengukuran kualitas udara
2. stasiun : Lokasi pengukuran di stasiun
3. pm10 : Partikulat salah satu parameter yang diukur
4. so2 : Sulfida (dalam bentuk SO2) salah satu parameter yang diukur
5. co : Carbon Monoksida salah satu parameter yand diukur
6. o3 : Ozon salah satu parameter yang diukur
7. no2 : NItrogen dioksida salah satu parameter yang diukur
8. max : Nilai ukur paling tinggi dari seluruh parameter yang diukur dalam waktu yang sama
9. critical : Parameter yang hasil pengukurannya paling tinggi
10. categori : Kategori hasil perhitungan indeks standar pencemaran udara

In [5]:
data_train_values = data_train.values

In [6]:
#Split data menjadi X_train,y_train
X_train, y_train = data_train_values[:, :-1], data_train_values[:, -1]

In [7]:
data_test_values = data_test.values

In [8]:
#Split data menjadi X_test,y_test
X_test, y_test = data_test_values[:, :-1], data_test_values[:, -1]

In [9]:
# Import libarary Logistic Regression
from sklearn.linear_model import LogisticRegression

from sklearn import linear_model
from sklearn.linear_model import SGDClassifier

# Import libarary KNN
from sklearn.neighbors import KNeighborsClassifier

# Import libarary Support Vector Machines dan linier Support Vector Machines
from sklearn.svm import LinearSVC

# Import libarary Gaussian Naive Bayes
from sklearn.naive_bayes import GaussianNB

In [10]:
# Import libarary confusion matrix
from sklearn.metrics import confusion_matrix

from sklearn.metrics import accuracy_score ,precision_score,recall_score,f1_score

In [11]:
gaussian = GaussianNB()
gaussian.fit(X_train, y_train)
Y_pred = gaussian.predict(X_test) 
accuracy_nb=round(accuracy_score(y_test,Y_pred)* 100, 2)
acc_gaussian = round(gaussian.score(X_train, y_train) * 100, 2)

cm = confusion_matrix(y_test, Y_pred)
accuracy = accuracy_score(y_test,Y_pred)
precision = precision_score(y_test, Y_pred,average='micro')
recall =  recall_score(y_test, Y_pred,average='micro')
f1 = f1_score(y_test,Y_pred,average='micro')
print('Confusion matrix for Naive Bayes\n',cm)
print('accuracy_Naive Bayes: %.3f' %accuracy)
print('precision_Naive Bayes: %.3f' %precision)
print('recall_Naive Bayes: %.3f' %recall)
print('f1-score_Naive Bayes : %.3f' %f1)

Confusion matrix for Naive Bayes
 [[ 29   0  15]
 [  0   8   1]
 [ 17   4 186]]
accuracy_Naive Bayes: 0.858
precision_Naive Bayes: 0.858
recall_Naive Bayes: 0.858
f1-score_Naive Bayes : 0.858


In [12]:
logreg = LogisticRegression(solver= 'lbfgs',max_iter=400)
logreg.fit(X_train, y_train)
Y_pred = logreg.predict(X_test)
accuracy_lr=round(accuracy_score(y_test,Y_pred)* 100, 2)
acc_log = round(logreg.score(X_train, y_train) * 100, 2)


cm = confusion_matrix(y_test, Y_pred)
accuracy = accuracy_score(y_test,Y_pred)
precision = precision_score(y_test, Y_pred,average='micro')
recall = recall_score(y_test, Y_pred,average='micro')
f1 = f1_score(y_test,Y_pred,average='micro')
print('Confusion matrix for Logistic Regression\n',cm)
print('accuracy_Logistic Regression : %.3f' %accuracy)
print('precision_Logistic Regression : %.3f' %precision)
print('recall_Logistic Regression: %.3f' %recall)
print('f1-score_Logistic Regression : %.3f' %f1)

Confusion matrix for Logistic Regression
 [[ 34   0  10]
 [  0   7   2]
 [ 62   2 143]]
accuracy_Logistic Regression : 0.708
precision_Logistic Regression : 0.708
recall_Logistic Regression: 0.708
f1-score_Logistic Regression : 0.708


In [13]:
linear_svc = LinearSVC(max_iter=4000)
linear_svc.fit(X_train, y_train)
Y_pred = linear_svc.predict(X_test)
accuracy_svc=round(accuracy_score(y_test,Y_pred)* 100, 2)
acc_linear_svc = round(linear_svc.score(X_train, y_train) * 100, 2)

cm = confusion_matrix(y_test, Y_pred)
accuracy = accuracy_score(y_test,Y_pred)
precision = precision_score(y_test, Y_pred,average='micro')
recall = recall_score(y_test, Y_pred,average='micro')
f1 = f1_score(y_test,Y_pred,average='micro')
print('Confusion matrix for SVC\n', cm)
print('accuracy_SVC: %.3f' %accuracy)
print('precision_SVC: %.3f' %precision)
print('recall_SVC: %.3f' %recall)
print('f1-score_SVC : %.3f' %f1)

Confusion matrix for SVC
 [[ 34   0  10]
 [  0   9   0]
 [ 77   7 123]]
accuracy_SVC: 0.638
precision_SVC: 0.638
recall_SVC: 0.638
f1-score_SVC : 0.638


In [14]:
knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(X_train, y_train)
Y_pred = knn.predict(X_test) 
accuracy_knn=round(accuracy_score(y_test,Y_pred)* 100, 2)
acc_knn = round(knn.score(X_train, y_train) * 100, 2)

cm = confusion_matrix(y_test, Y_pred)
accuracy = accuracy_score(y_test,Y_pred)
precision = precision_score(y_test, Y_pred,average='micro')
recall = recall_score(y_test, Y_pred,average='micro')
f1 = f1_score(y_test,Y_pred,average='micro')
print('Confusion matrix for KNN\n',cm)
print('accuracy_KNN : %.3f' %accuracy)
print('precision_KNN : %.3f' %precision)
print('recall_KNN: %.3f' %recall)
print('f1-score_KNN : %.3f' %f1)

Confusion matrix for KNN
 [[ 43   0   1]
 [  0   7   2]
 [ 20   3 184]]
accuracy_KNN : 0.900
precision_KNN : 0.900
recall_KNN: 0.900
f1-score_KNN : 0.900


In [15]:
results = pd.DataFrame({
    'Model': [ 'KNN', 
              'Logistic Regression',
              'Naive Bayes',  
              ' Support Vector Machine'],
    'Score': [ acc_knn,
              acc_log,
              acc_gaussian,  
              acc_linear_svc],
    "Accuracy_score":[accuracy_knn,
                      accuracy_lr,
                      accuracy_nb,
                      accuracy_svc
                     ]})
result_df = results.sort_values(by='Accuracy_score', ascending=False)
result_df = results.reset_index(drop=True)
result_df.head(9)

Model  Score  Accuracy_score
0                      KNN  99.53           90.00
1      Logistic Regression  96.82           70.77
2              Naive Bayes  95.84           85.77
3   Support Vector Machine  91.73           63.85

Dikarenakan datanya imbalanced, maka akan dilakukan over sampling terhadap data class label yang minoritas

## Tuning Hyperparameter

In [16]:
# Tuning menggunakan GridSearchCV
from sklearn.model_selection import GridSearchCV

#### Tuning KNN

In [17]:
#List Hyperparameters that we want to tune
leaf_size = list(range(1,5))
n_neighbors = list(range(1,15))
p=[1,2]

#Convert to dictionary
hyperparameters = dict(leaf_size=leaf_size, n_neighbors=n_neighbors, p=p)

#Create new KNN object
knn_2 = KNeighborsClassifier()

#Use GridSearch
clf = GridSearchCV(knn_2, hyperparameters, cv=10)

#Fit the model
best_model = clf.fit(X_train, y_train)

#Print The value of best Hyperparameters
print('Best leaf_size:', best_model.best_estimator_.get_params()['leaf_size'])
print('Best p:', best_model.best_estimator_.get_params()['p'])
print('Best n_neighbors:', best_model.best_estimator_.get_params()['n_neighbors'])

Best leaf_size: 1
Best p: 1
Best n_neighbors: 1


Hasil dari Hyperparameter KNN di atas di implementasikan dalam model

In [18]:
knn_3 = KNeighborsClassifier(n_neighbors = 1, leaf_size = 1, p = 1)
knn_3.fit(X_train, y_train)
Y_pred = knn_3.predict(X_test) 
accuracy_knn_3=round(accuracy_score(y_test,Y_pred)* 100, 2)
acc_knn_3 = round(knn_3.score(X_train, y_train) * 100, 2)

cm = confusion_matrix(y_test, Y_pred)
accuracy = accuracy_score(y_test,Y_pred)
precision = precision_score(y_test, Y_pred,average='micro')
recall = recall_score(y_test, Y_pred,average='micro')
f1 = f1_score(y_test,Y_pred,average='micro')
print('Confusion matrix for KNN\n',cm)
print('accuracy_KNN : %.3f' %accuracy)
print('precision_KNN : %.3f' %precision)
print('recall_KNN: %.3f' %recall)
print('f1-score_KNN : %.3f' %f1)

Confusion matrix for KNN
 [[ 42   0   2]
 [  0   7   2]
 [ 11   5 191]]
accuracy_KNN : 0.923
precision_KNN : 0.923
recall_KNN: 0.923
f1-score_KNN : 0.923


#### Tuning Logistic Regression

In [19]:
#List Hyperparameters yang akan diuji
penalty = ['l1', 'l2']
C = np.logspace(-4,4,20)
#Menjadikan ke dalam bentuk dictionary
hyperparameters = dict(penalty=penalty, C=C)
#Membuat Object Logistic Regression
logreg = LogisticRegression(solver= 'lbfgs',max_iter=400)
#Memasukan ke Grid Search
#CV itu Cross Validation
#Menggunakan 10-Fold CV
clf = GridSearchCV(logreg, hyperparameters, cv=10)
#Fitting Model
best_model = clf.fit(X_train,y_train)
#Nilai hyperparameters terbaik
print('Best Penalty:', best_model.best_estimator_.get_params()['penalty'])
print('Best C:', best_model.best_estimator_.get_params()['C'])

Best Penalty: l2
Best C: 0.012742749857031334


Hasil dari Hyperparameter Logistic Regression di atas di implementasikan dalam model

In [20]:
logreg3 = LogisticRegression(solver= 'lbfgs',max_iter=400, penalty='l2', C=0.012742749857031334)
logreg3.fit(X_train, y_train)
Y_pred = logreg3.predict(X_test)
accuracy_lr3=round(accuracy_score(y_test,Y_pred)* 100, 2)
acc_log3 = round(logreg3.score(X_train, y_train) * 100, 2)


cm = confusion_matrix(y_test, Y_pred)
accuracy = accuracy_score(y_test,Y_pred)
precision = precision_score(y_test, Y_pred,average='micro')
recall = recall_score(y_test, Y_pred,average='micro')
f1 = f1_score(y_test,Y_pred,average='micro')
print('Confusion matrix for Logistic Regression\n',cm)
print('accuracy_Logistic Regression : %.3f' %accuracy)
print('precision_Logistic Regression : %.3f' %precision)
print('recall_Logistic Regression: %.3f' %recall)
print('f1-score_Logistic Regression : %.3f' %f1)

Confusion matrix for Logistic Regression
 [[ 44   0   0]
 [  0   9   0]
 [ 50   0 157]]
accuracy_Logistic Regression : 0.808
precision_Logistic Regression : 0.808
recall_Logistic Regression: 0.808
f1-score_Logistic Regression : 0.808


#### Tuning Gaussian Naive Bayes

In [21]:
param_grid_nb = {
    'var_smoothing': np.logspace(0,-9, num=100)
}

nbModel_grid = GridSearchCV(estimator=GaussianNB(), param_grid=param_grid_nb, verbose=1, cv=10, n_jobs=-1)
nbModel_grid.fit(X_train, y_train)
print(nbModel_grid.best_estimator_)

Fitting 10 folds for each of 100 candidates, totalling 1000 fits
GaussianNB(var_smoothing=0.0012328467394420659)


Hasil dari Hyperparameter Gaussian Naive Bayes di atas di implementasikan dalam model

In [22]:
gaussian3 = GaussianNB(var_smoothing=0.0012328467394420659)
gaussian3.fit(X_train, y_train)
Y_pred = gaussian3.predict(X_test) 
accuracy_nb3=round(accuracy_score(y_test,Y_pred)* 100, 2)
acc_gaussian3 = round(gaussian3.score(X_train, y_train) * 100, 2)

cm = confusion_matrix(y_test, Y_pred)
accuracy = accuracy_score(y_test,Y_pred)
precision = precision_score(y_test, Y_pred,average='micro')
recall =  recall_score(y_test, Y_pred,average='micro')
f1 = f1_score(y_test,Y_pred,average='micro')
print('Confusion matrix for Naive Bayes\n',cm)
print('accuracy_Naive Bayes: %.3f' %accuracy)
print('precision_Naive Bayes: %.3f' %precision)
print('recall_Naive Bayes: %.3f' %recall)
print('f1-score_Naive Bayes : %.3f' %f1)

Confusion matrix for Naive Bayes
 [[ 41   0   3]
 [  0   8   1]
 [ 21   2 184]]
accuracy_Naive Bayes: 0.896
precision_Naive Bayes: 0.896
recall_Naive Bayes: 0.896
f1-score_Naive Bayes : 0.896


In [23]:
results = pd.DataFrame({
    'Model': [ 'KNN', 
              'Logistic Regression',
              'Naive Bayes',  
              ' Support Vector Machine'],
    'Score': [ acc_knn,
              acc_log,
              acc_gaussian,  
              acc_linear_svc],
    "Accuracy_score":[accuracy_knn,
                      accuracy_lr,
                      accuracy_nb,
                      accuracy_svc],
    "Score after Tuning":[acc_knn_3,
                          acc_log3,
                          acc_gaussian3,  
                          ''],
    "Accuracy_score after tuning":[accuracy_knn_3,
                      accuracy_lr3,
                      accuracy_nb3,
                      ''
                     ]})
result_df = results.sort_values(by='Accuracy_score', ascending=False)
result_df = results.reset_index(drop=True)
result_df.head(9)

Model  Score  Accuracy_score Score after Tuning  \
0                      KNN  99.53           90.00              100.0   
1      Logistic Regression  96.82           70.77               98.9   
2              Naive Bayes  95.84           85.77              96.06   
3   Support Vector Machine  91.73           63.85                      

  Accuracy_score after tuning  
0                       92.31  
1                       80.77  
2                       89.62  
3